### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by jftuga** [jftuga/freq#2]
```
c:\> dir | freq -ss 2

panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.ReadInput(0xc00007bf08, 0x0, 0x2, 0x0, 0x16)
	/home/jftuga/go/src/github.com/jftuga/freq/freq.go:151 +0x58b
main.main()
	/home/jftuga/go/src/github.com/jftuga/freq/freq.go:228 +0x3dc
```

**Comment by jftuga** [comment]
This is fixed in v1.7.2
